<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Platforms>AnyCPU;x86</Platforms>
    <PlatformTarget>x86</PlatformTarget>
    <AssemblyName>GmmkProfileSwitcher</AssemblyName>
    <RootNamespace>GmmkProfileSwitcher</RootNamespace>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GmmkProfileSwitcherLib\GmmkProfileSwitcherLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="app.ico" />
  </ItemGroup>

</Project>